const ACTIONS = {
    SET_SESSION: 'SET_SESSION',
    SET_KHALED_SESSION: 'SET_KHALED_SESSION',
    SET_ERROR: 'SET_ERROR',
    SET_SUCCESS: 'SET_SUCCESS',
    SET_NAV: 'SET_NAV',

}


export {ACTIONS};